# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
- repo: self


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'Sonar'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'DevSecOps'
        cliProjectName: 'DevSecOps'
        cliSources: '.'

    #Module-4 - Exercise 2
    - task: SonarQubeAnalyze@4
      displayName: 'Run Code Analysis'

    #Module-4 - Exercise 2
    - task: SonarQubePublish@4
      displayName: 'Publish Quality Gate Result'
      inputs:
        pollingTimeoutSec: '300'